import "dotenv/config";
import { Category, Prisma, PrismaClient, Status } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const DEMO_USER_EMAIL = "demo@arca.com";
const DEMO_USER_NAME = "Usu\u00e1rio Demo";
const DEMO_USER_PASSWORD = "12345678";

type SeedSpecies = {
  uniqueIdentifier: string;
  commonName: string;
  scientificName: string;
  category: Category;
  status: Status;
  latitude: number;
  longitude: number;
  location: string;
  observationDate: Date;
  abundance: number;
  notes: string;
  weatherData: Prisma.InputJsonValue;
};

function observationDate(value: string): Date {
  return new Date(`${value}T12:00:00.000Z`);
}

function weatherData(
  temperature: number,
  windspeed: number,
  weathercode: number,
  date: string
): Prisma.InputJsonValue {
  return {
    temperature,
    windspeed,
    weathercode,
    time: `${date}T12:00`,
    source: "seed",
  };
}

const speciesData: SeedSpecies[] = [
  {
    uniqueIdentifier: "arca-seed-arara-azul-grande",
    commonName: "Arara-azul-grande",
    scientificName: "Anodorhynchus hyacinthinus",
    category: Category.Bird,
    status: Status.Endangered,
    latitude: -19.0088,
    longitude: -57.651,
    location: "Pantanal, Corumba - MS",
    observationDate: observationDate("2026-01-18"),
    abundance: 3,
    notes: "Casal observado em area de buritizal durante monitoramento matinal.",
    weatherData: weatherData(31.4, 9.8, 2, "2026-01-18"),
  },
  {
    uniqueIdentifier: "arca-seed-tucano-toco",
    commonName: "Tucano-toco",
    scientificName: "Ramphastos toco",
    category: Category.Bird,
    status: Status.Active,
    latitude: -15.4606,
    longitude: -55.7498,
    location: "Chapada dos Guimaraes - MT",
    observationDate: observationDate("2026-04-07"),
    abundance: 7,
    notes: "Grupo vocalizando proximo a trilha de cerrado rupestre.",
    weatherData: weatherData(27.8, 6.4, 1, "2026-04-07"),
  },
  {
    uniqueIdentifier: "arca-seed-guara",
    commonName: "Guara",
    scientificName: "Eudocimus ruber",
    category: Category.Bird,
    status: Status.Active,
    latitude: -1.4575,
    longitude: -45.1203,
    location: "Reentrancias Maranhenses - MA",
    observationDate: observationDate("2025-11-22"),
    abundance: 9,
    notes: "Bando alimentando-se em planicie de mare baixa.",
    weatherData: weatherData(29.2, 11.1, 3, "2025-11-22"),
  },
  {
    uniqueIdentifier: "arca-seed-mutum-de-alagoas",
    commonName: "Mutum-de-alagoas",
    scientificName: "Pauxi mitu",
    category: Category.Bird,
    status: Status.Extinct,
    latitude: -9.6658,
    longitude: -35.7353,
    location: "Mata Atlantica de Alagoas - AL",
    observationDate: observationDate("2026-02-12"),
    abundance: 1,
    notes: "Registro historico para demonstrar filtros de status e conservacao.",
    weatherData: weatherData(26.6, 8.2, 61, "2026-02-12"),
  },
  {
    uniqueIdentifier: "arca-seed-harpia",
    commonName: "Harpia",
    scientificName: "Harpia harpyja",
    category: Category.Bird,
    status: Status.Endangered,
    latitude: -3.1445,
    longitude: -54.9359,
    location: "Floresta Nacional do Tapajos - PA",
    observationDate: observationDate("2026-03-03"),
    abundance: 2,
    notes: "Individuo adulto registrado por vocalizacao e avistamento breve.",
    weatherData: weatherData(28.1, 5.7, 80, "2026-03-03"),
  },
  {
    uniqueIdentifier: "arca-seed-bem-te-vi",
    commonName: "Bem-te-vi",
    scientificName: "Pitangus sulphuratus",
    category: Category.Bird,
    status: Status.Active,
    latitude: -23.5874,
    longitude: -46.6576,
    location: "Parque Ibirapuera, Sao Paulo - SP",
    observationDate: observationDate("2026-05-01"),
    abundance: 10,
    notes: "Especie urbana abundante em area de lago e jardins.",
    weatherData: weatherData(22.4, 10.5, 2, "2026-05-01"),
  },
  {
    uniqueIdentifier: "arca-seed-pirarucu",
    commonName: "Pirarucu",
    scientificName: "Arapaima gigas",
    category: Category.Fish,
    status: Status.Active,
    latitude: -3.1137,
    longitude: -64.7978,
    location: "Reserva Mamiraua - AM",
    observationDate: observationDate("2025-08-14"),
    abundance: 6,
    notes: "Contagem visual em lago de varzea com manejo comunitario.",
    weatherData: weatherData(30.2, 4.6, 1, "2025-08-14"),
  },
  {
    uniqueIdentifier: "arca-seed-dourado",
    commonName: "Dourado",
    scientificName: "Salminus brasiliensis",
    category: Category.Fish,
    status: Status.Inactive,
    latitude: -21.9846,
    longitude: -47.4254,
    location: "Rio Mogi-Guacu - SP",
    observationDate: observationDate("2025-06-02"),
    abundance: 4,
    notes: "Registro pausado para revisao de ponto amostral no trecho de corredeira.",
    weatherData: weatherData(20.1, 7.9, 45, "2025-06-02"),
  },
  {
    uniqueIdentifier: "arca-seed-tambaqui",
    commonName: "Tambaqui",
    scientificName: "Colossoma macropomum",
    category: Category.Fish,
    status: Status.Active,
    latitude: -3.3495,
    longitude: -60.6286,
    location: "Rio Solimoes - AM",
    observationDate: observationDate("2026-01-29"),
    abundance: 8,
    notes: "Cardume observado em area de igapo durante cheia sazonal.",
    weatherData: weatherData(29.9, 6.2, 3, "2026-01-29"),
  },
  {
    uniqueIdentifier: "arca-seed-mero",
    commonName: "Mero",
    scientificName: "Epinephelus itajara",
    category: Category.Fish,
    status: Status.Endangered,
    latitude: -17.9635,
    longitude: -38.6915,
    location: "Parque Nacional Marinho dos Abrolhos - BA",
    observationDate: observationDate("2025-10-09"),
    abundance: 2,
    notes: "Individuos juvenis em recife costeiro com boa visibilidade.",
    weatherData: weatherData(25.6, 18.3, 2, "2025-10-09"),
  },
  {
    uniqueIdentifier: "arca-seed-cavalo-marinho",
    commonName: "Cavalo-marinho",
    scientificName: "Hippocampus reidi",
    category: Category.Fish,
    status: Status.Endangered,
    latitude: -6.2285,
    longitude: -35.0492,
    location: "Praia de Pipa - RN",
    observationDate: observationDate("2026-04-21"),
    abundance: 3,
    notes: "Monitoramento em area de pradaria marinha rasa.",
    weatherData: weatherData(28.7, 16.9, 1, "2026-04-21"),
  },
  {
    uniqueIdentifier: "arca-seed-sardinha-verdadeira",
    commonName: "Sardinha-verdadeira",
    scientificName: "Sardinella brasiliensis",
    category: Category.Fish,
    status: Status.Active,
    latitude: -23.0733,
    longitude: -44.1862,
    location: "Baia da Ilha Grande - RJ",
    observationDate: observationDate("2025-12-05"),
    abundance: 10,
    notes: "Alta concentracao detectada em levantamento costeiro.",
    weatherData: weatherData(24.8, 13.5, 3, "2025-12-05"),
  },
  {
    uniqueIdentifier: "arca-seed-pau-brasil",
    commonName: "Pau-brasil",
    scientificName: "Paubrasilia echinata",
    category: Category.Plant,
    status: Status.Endangered,
    latitude: -19.0364,
    longitude: -40.1428,
    location: "Reserva Biologica de Sooretama - ES",
    observationDate: observationDate("2025-09-20"),
    abundance: 4,
    notes: "Individuos adultos mapeados em fragmento de Mata Atlantica.",
    weatherData: weatherData(24.9, 6.1, 51, "2025-09-20"),
  },
  {
    uniqueIdentifier: "arca-seed-vitoria-regia",
    commonName: "Vitoria-regia",
    scientificName: "Victoria amazonica",
    category: Category.Plant,
    status: Status.Active,
    latitude: -3.2038,
    longitude: -60.2254,
    location: "Lago Janauari - AM",
    observationDate: observationDate("2026-02-05"),
    abundance: 7,
    notes: "Folhas distribuidas em lago de aguas calmas proximo ao Solimoes.",
    weatherData: weatherData(30.6, 5.4, 2, "2026-02-05"),
  },
  {
    uniqueIdentifier: "arca-seed-araucaria",
    commonName: "Araucaria",
    scientificName: "Araucaria angustifolia",
    category: Category.Plant,
    status: Status.Endangered,
    latitude: -28.2937,
    longitude: -49.9312,
    location: "Sao Joaquim - SC",
    observationDate: observationDate("2025-07-18"),
    abundance: 5,
    notes: "Talhao misto em area de altitude com regeneracao natural.",
    weatherData: weatherData(11.8, 12.7, 45, "2025-07-18"),
  },
  {
    uniqueIdentifier: "arca-seed-ipe-amarelo",
    commonName: "Ipe-amarelo",
    scientificName: "Handroanthus albus",
    category: Category.Plant,
    status: Status.Active,
    latitude: -15.7998,
    longitude: -47.8645,
    location: "Brasilia - DF",
    observationDate: observationDate("2026-03-24"),
    abundance: 9,
    notes: "Florada registrada em area urbana arborizada.",
    weatherData: weatherData(25.3, 10.1, 1, "2026-03-24"),
  },
  {
    uniqueIdentifier: "arca-seed-mandacaru",
    commonName: "Mandacaru",
    scientificName: "Cereus jamacaru",
    category: Category.Plant,
    status: Status.Active,
    latitude: -8.8458,
    longitude: -42.5513,
    location: "Serra da Capivara - PI",
    observationDate: observationDate("2025-05-11"),
    abundance: 8,
    notes: "Populacao saudavel em afloramento rochoso de caatinga.",
    weatherData: weatherData(32.1, 14.2, 0, "2025-05-11"),
  },
  {
    uniqueIdentifier: "arca-seed-palmeira-jucara",
    commonName: "Palmeira-jucara",
    scientificName: "Euterpe edulis",
    category: Category.Plant,
    status: Status.Endangered,
    latitude: -23.347,
    longitude: -45.0954,
    location: "Parque Estadual da Serra do Mar - SP",
    observationDate: observationDate("2026-04-02"),
    abundance: 3,
    notes: "Nucleo em recuperacao acompanhado por trilha permanente.",
    weatherData: weatherData(19.7, 8.8, 61, "2026-04-02"),
  },
  {
    uniqueIdentifier: "arca-seed-onca-pintada",
    commonName: "Onca-pintada",
    scientificName: "Panthera onca",
    category: Category.Mammal,
    status: Status.Endangered,
    latitude: -16.2639,
    longitude: -56.6228,
    location: "Pantanal, Pocone - MT",
    observationDate: observationDate("2026-01-07"),
    abundance: 2,
    notes: "Rastros recentes e imagem de camera trap na mata ciliar.",
    weatherData: weatherData(30.8, 7.4, 2, "2026-01-07"),
  },
  {
    uniqueIdentifier: "arca-seed-mico-leao-dourado",
    commonName: "Mico-leao-dourado",
    scientificName: "Leontopithecus rosalia",
    category: Category.Mammal,
    status: Status.Endangered,
    latitude: -22.5266,
    longitude: -42.2797,
    location: "Reserva Biologica Poco das Antas - RJ",
    observationDate: observationDate("2025-08-27"),
    abundance: 4,
    notes: "Grupo familiar monitorado em corredor restaurado.",
    weatherData: weatherData(23.4, 5.9, 51, "2025-08-27"),
  },
  {
    uniqueIdentifier: "arca-seed-capivara",
    commonName: "Capivara",
    scientificName: "Hydrochoerus hydrochaeris",
    category: Category.Mammal,
    status: Status.Active,
    latitude: -19.8517,
    longitude: -43.9738,
    location: "Lagoa da Pampulha - MG",
    observationDate: observationDate("2026-05-03"),
    abundance: 10,
    notes: "Grupo numeroso observado em margem gramada urbana.",
    weatherData: weatherData(21.9, 6.7, 2, "2026-05-03"),
  },
  {
    uniqueIdentifier: "arca-seed-lobo-guara",
    commonName: "Lobo-guara",
    scientificName: "Chrysocyon brachyurus",
    category: Category.Mammal,
    status: Status.Endangered,
    latitude: -20.235,
    longitude: -46.608,
    location: "Serra da Canastra - MG",
    observationDate: observationDate("2025-06-16"),
    abundance: 2,
    notes: "Registro noturno em area de campo limpo proxima a nascente.",
    weatherData: weatherData(17.6, 9.1, 0, "2025-06-16"),
  },
  {
    uniqueIdentifier: "arca-seed-boto-cor-de-rosa",
    commonName: "Boto-cor-de-rosa",
    scientificName: "Inia geoffrensis",
    category: Category.Mammal,
    status: Status.Endangered,
    latitude: -3.1019,
    longitude: -60.025,
    location: "Rio Negro, Manaus - AM",
    observationDate: observationDate("2026-02-19"),
    abundance: 5,
    notes: "Individuos observados em canal principal durante subida das aguas.",
    weatherData: weatherData(30.4, 5.6, 3, "2026-02-19"),
  },
  {
    uniqueIdentifier: "arca-seed-rato-candango",
    commonName: "Rato-candango",
    scientificName: "Juscelinomys candango",
    category: Category.Mammal,
    status: Status.Extinct,
    latitude: -15.9167,
    longitude: -47.8333,
    location: "Cerrado do Distrito Federal - DF",
    observationDate: observationDate("2025-11-12"),
    abundance: 1,
    notes: "Registro historico usado para exercitar status Extinct no dashboard.",
    weatherData: weatherData(24.2, 8.3, 2, "2025-11-12"),
  },
  {
    uniqueIdentifier: "arca-seed-tartaruga-verde",
    commonName: "Tartaruga-verde",
    scientificName: "Chelonia mydas",
    category: Category.Reptile,
    status: Status.Endangered,
    latitude: -3.8549,
    longitude: -32.4233,
    location: "Fernando de Noronha - PE",
    observationDate: observationDate("2026-03-11"),
    abundance: 4,
    notes: "Avistamento em area de alimentacao costeira protegida.",
    weatherData: weatherData(28.3, 20.4, 1, "2026-03-11"),
  },
  {
    uniqueIdentifier: "arca-seed-jacare-acu",
    commonName: "Jacare-acu",
    scientificName: "Melanosuchus niger",
    category: Category.Reptile,
    status: Status.Active,
    latitude: -2.8623,
    longitude: -64.9057,
    location: "Reserva Mamiraua - AM",
    observationDate: observationDate("2025-09-03"),
    abundance: 6,
    notes: "Contagem noturna em margem de lago de varzea.",
    weatherData: weatherData(29.7, 4.1, 2, "2025-09-03"),
  },
  {
    uniqueIdentifier: "arca-seed-jararaca",
    commonName: "Jararaca",
    scientificName: "Bothrops jararaca",
    category: Category.Reptile,
    status: Status.Active,
    latitude: -25.5122,
    longitude: -48.8226,
    location: "Serra do Mar - PR",
    observationDate: observationDate("2026-04-26"),
    abundance: 3,
    notes: "Individuo registrado em borda de trilha apos chuva.",
    weatherData: weatherData(18.8, 7.6, 63, "2026-04-26"),
  },
  {
    uniqueIdentifier: "arca-seed-tartaruga-da-amazonia",
    commonName: "Tartaruga-da-Amazonia",
    scientificName: "Podocnemis expansa",
    category: Category.Reptile,
    status: Status.Endangered,
    latitude: -1.3917,
    longitude: -56.4967,
    location: "Rio Trombetas - PA",
    observationDate: observationDate("2025-10-28"),
    abundance: 5,
    notes: "Ninhos monitorados em praia fluvial durante vazante.",
    weatherData: weatherData(31.1, 5.3, 2, "2025-10-28"),
  },
  {
    uniqueIdentifier: "arca-seed-calango",
    commonName: "Calango",
    scientificName: "Tropidurus hispidus",
    category: Category.Reptile,
    status: Status.Active,
    latitude: -9.4161,
    longitude: -40.503,
    location: "Caatinga de Juazeiro - BA",
    observationDate: observationDate("2025-12-14"),
    abundance: 8,
    notes: "Populacao ativa em rochas expostas de area semiarida.",
    weatherData: weatherData(33.4, 13.8, 0, "2025-12-14"),
  },
  {
    uniqueIdentifier: "arca-seed-cobra-coral-verdadeira",
    commonName: "Cobra-coral-verdadeira",
    scientificName: "Micrurus corallinus",
    category: Category.Reptile,
    status: Status.Inactive,
    latitude: -24.0091,
    longitude: -47.9903,
    location: "Parque Estadual Carlos Botelho - SP",
    observationDate: observationDate("2026-01-26"),
    abundance: 1,
    notes: "Ponto temporariamente inativo por restricao de acesso a trilha.",
    weatherData: weatherData(20.5, 6.9, 61, "2026-01-26"),
  },
  {
    uniqueIdentifier: "arca-seed-borboleta-azul",
    commonName: "Borboleta-azul",
    scientificName: "Morpho menelaus",
    category: Category.Other,
    status: Status.Active,
    latitude: -2.9502,
    longitude: -59.9617,
    location: "Reserva Ducke - AM",
    observationDate: observationDate("2026-02-28"),
    abundance: 7,
    notes: "Adultos em voo baixo ao longo de clareira na floresta.",
    weatherData: weatherData(29.5, 4.8, 80, "2026-02-28"),
  },
  {
    uniqueIdentifier: "arca-seed-coral-cerebro",
    commonName: "Coral-cerebro",
    scientificName: "Mussismilia hispida",
    category: Category.Other,
    status: Status.Endangered,
    latitude: -16.395,
    longitude: -39.0395,
    location: "Recife de Fora - BA",
    observationDate: observationDate("2025-04-18"),
    abundance: 4,
    notes: "Colonias acompanhadas em transecto recifal de aguas rasas.",
    weatherData: weatherData(26.3, 15.6, 2, "2025-04-18"),
  },
  {
    uniqueIdentifier: "arca-seed-caranguejo-uca",
    commonName: "Caranguejo-uca",
    scientificName: "Ucides cordatus",
    category: Category.Other,
    status: Status.Active,
    latitude: -25.0144,
    longitude: -47.9268,
    location: "Manguezal de Cananeia - SP",
    observationDate: observationDate("2025-07-05"),
    abundance: 9,
    notes: "Tocas ativas contadas em parcela de manguezal preservado.",
    weatherData: weatherData(18.9, 9.7, 51, "2025-07-05"),
  },
  {
    uniqueIdentifier: "arca-seed-abelha-sem-ferrao",
    commonName: "Abelha-sem-ferrao",
    scientificName: "Melipona scutellaris",
    category: Category.Other,
    status: Status.Endangered,
    latitude: -8.2858,
    longitude: -35.9821,
    location: "Zona da Mata - PE",
    observationDate: observationDate("2026-03-29"),
    abundance: 5,
    notes: "Ninhos monitorados em sistema agroflorestal com floracao ativa.",
    weatherData: weatherData(27.1, 7.2, 3, "2026-03-29"),
  },
  {
    uniqueIdentifier: "arca-seed-estrela-do-mar-vermelha",
    commonName: "Estrela-do-mar-vermelha",
    scientificName: "Echinaster brasiliensis",
    category: Category.Other,
    status: Status.Inactive,
    latitude: -22.9669,
    longitude: -42.0278,
    location: "Arraial do Cabo - RJ",
    observationDate: observationDate("2025-11-30"),
    abundance: 3,
    notes: "Monitoramento suspenso temporariamente por baixa visibilidade.",
    weatherData: weatherData(23.6, 17.8, 3, "2025-11-30"),
  },
  {
    uniqueIdentifier: "arca-seed-coral-sol",
    commonName: "Coral-sol",
    scientificName: "Tubastraea coccinea",
    category: Category.Other,
    status: Status.Inactive,
    latitude: -23.1453,
    longitude: -44.2381,
    location: "Baia da Ilha Grande - RJ",
    observationDate: observationDate("2026-04-12"),
    abundance: 6,
    notes: "Especie exotica invasora mantida para acompanhamento de controle.",
    weatherData: weatherData(24.1, 14.4, 2, "2026-04-12"),
  },
];

async function main(): Promise<void> {
  const password = await bcrypt.hash(DEMO_USER_PASSWORD, 10);

  const demoUser = await prisma.user.upsert({
    where: { email: DEMO_USER_EMAIL },
    update: {
      name: DEMO_USER_NAME,
      password,
    },
    create: {
      email: DEMO_USER_EMAIL,
      name: DEMO_USER_NAME,
      password,
    },
  });

  await prisma.$transaction(
    speciesData.map((species) =>
      prisma.species.upsert({
        where: { uniqueIdentifier: species.uniqueIdentifier },
        update: {
          commonName: species.commonName,
          scientificName: species.scientificName,
          category: species.category,
          status: species.status,
          latitude: species.latitude,
          longitude: species.longitude,
          location: species.location,
          observationDate: species.observationDate,
          abundance: species.abundance,
          notes: species.notes,
          weatherData: species.weatherData,
          createdById: demoUser.id,
        },
        create: {
          ...species,
          createdById: demoUser.id,
        },
      })
    )
  );

  console.log(`Seed completed: ${DEMO_USER_EMAIL} and ${speciesData.length} species ready.`);
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
